export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const FETCH_USER_REPORTS = 'FETCH_USER_REPORTS';
export const FETCH_USER_TEMPLATES = 'FETCH_USER_TEMPLATES';
export const FETCH_TEMPLATES = 'FETCH_TEMPLATES';
