export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const FETCH_USER_REPORTS = 'FETCH_USER_REPORTS';
export const FETCH_USER_ALL_REPORTS = 'FETCH_USER_ALL_REPORTS';
export const FETCH_APPROVAL_REQUESTS = 'FETCH_APPROVAL_REQUESTS';
export const FETCH_USER_TEMPLATES = 'FETCH_USER_TEMPLATES';
export const FETCH_TEMPLATES = 'FETCH_TEMPLATES';
export const ADD_NEW_REPORT = 'ADD_NEW_REPORT';
